modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"
issueTrackerURL = "https://github.com/playerroutes/issues"

[[mods]]
modId = "playerroutes"
version = "${file.jarVersion}"
displayName = "Player Routes"
authors = "PlayerRoutes Team"
description = '''
Server-side mod that tracks player routes and exposes them via WebSocket for a web map interface.
'''

[[dependencies.playerroutes]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.playerroutes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "SERVER"
